# Generated by Django 5.2.1 on 2025-05-24 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Planta',
                'verbose_name_plural': 'Tipos de Planta',
                'db_table': 'TipoPlanta',
            },
        ),
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placa',
                'verbose_name_plural': 'Placas',
                'db_table': 'Placa',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.placa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoplanta')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'db_table': 'Planta',
            },
        ),
        migrations.CreateModel(
            name='Riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('luz_intencidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planta')),
            ],
            options={
                'verbose_name': 'Riego',
                'verbose_name_plural': 'Riegos',
                'db_table': 'Riego',
            },
        ),
    ]
