# Generated by Django 5.2.1 on 2025-05-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='riego',
            name='volumen_salida',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
