# Generated by Django 5.2.1 on 2025-05-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_planta_imagen_planta_nombre_riego_volumen_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riego',
            name='volumen_salida',
        ),
    ]
