# Generated by Django 5.2.1 on 2025-05-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_riego_volumen_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='riego',
            name='volumen_salida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
