# Generated by Django 5.2.1 on 2025-05-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_riego_volumen_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temperatura (°C)'),
        ),
    ]
