# Generated by Django 5.2.1 on 2025-05-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_planta_humedad_planta_temperatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='codigo_placa',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Código de placa'),
        ),
    ]
